// <auto-generated />
using System;
using Autoszerelo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Autoszerelo.Migrations
{
    [DbContext(typeof(AutoszereloDbContext))]
    [Migration("20240524101134_LazyLoad")]
    partial class LazyLoad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Autoszerelo.DataClasses.Munka", b =>
                {
                    b.Property<Guid>("MunkaAzonosito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("GyartasiEv")
                        .HasColumnType("date");

                    b.Property<string>("HibaRovidLeirasa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HibaSulyossaga")
                        .HasColumnType("int");

                    b.Property<int>("MunkaAllapot")
                        .HasColumnType("int");

                    b.Property<int>("MunkaKategoria")
                        .HasColumnType("int");

                    b.Property<string>("Rendszam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UgyfelSzam")
                        .HasColumnType("char(36)");

                    b.HasKey("MunkaAzonosito");

                    b.ToTable("Munkak");
                });

            modelBuilder.Entity("Autoszerelo.DataClasses.Ugyfel", b =>
                {
                    b.Property<Guid>("Ugyfelszam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lakcim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Ugyfelszam");

                    b.ToTable("Ugyfelek");
                });
#pragma warning restore 612, 618
        }
    }
}
